### ISSUE TITLE
Swankage 100% cpu / Slow draw on Linux64 with Intel X.org driver

### ISSUE THREAD

**Issue by truck** [xriss/swankypaint#10]
Unsure what's going on, but swankage is eating 100% of _1_ of 2 cpu's, not using the other, and seems to be unable to draw faster than 1 frame per 10 seconds.  It does appear to be _frames_ though, not pixels, in that the gui / etc all come up in chunks.  We've seen this before in earlier builds.

Profiling with 'perf' shows me the calls, and just about everything in the first 50 calls is all using the 915 xorg module, but I'll bet I need a debug version of gamecake to really help here and see what's _actually_ calling it, not an assembly output or an offset label.  So that ol' gamecake compile thing would be useful (:

valgrind runs out of memory when attempting to profile it, which is interesting in that apparently it is eating more than 3 GB of ram to do this.

**Comment by xriss** [comment]
Its possibly software emulating OpenGLES...

Which does work, but is also rather slow.

Beware of linking to anything called swrast :)

**Comment by truck** [comment]
oh that is probably exactly what it is.  I shall endeavor to find a solution for that (:
