### ISSUE TITLE
Swankypaint won't launch on osx – El Capitan

### ISSUE THREAD

**Issue by oddeye** [xriss/swankypaint#12]
Hi, 

after update to El Capitan I'm not able to start the application.

Error log:

The flavour of win is osx
./gamecake.osx: [string "gles"]:638: attempt to index local 's' (a nil value)
stack traceback:
	[string "gles"]:638: in function 'GetExtensions'
	...dra/Downloads/swankypaint/lua/wetgenes/gamecake/gles.lua:19: in function 'bake'
	...dra/Downloads/swankypaint/lua/wetgenes/gamecake/oven.lua:246: in function 'rebake'
	...dra/Downloads/swankypaint/lua/wetgenes/gamecake/cake.lua:53: in function 'bake'
	...dra/Downloads/swankypaint/lua/wetgenes/gamecake/oven.lua:246: in function 'rebake'
	...dra/Downloads/swankypaint/lua/wetgenes/gamecake/oven.lua:209: in function 'preheat'
	[string "--#!/usr/local/bin/gamecake..."]:25: in function 'func'
	[string "start"]:44: in main chunk
	[C]: at 0x00235340
	[C]: at 0x00003010

Any ideas what to do?

**Comment by notshi** [comment]
Hi @oddeye, thanks for the bug report.

We're looking into updating to El Capitan to find out what's going on. At the moment, it seems that the recent update in El Capitan has changed OpenGL to not return extension strings which is causing a NULL crash because we're assuming there should be some strings returned.

Will report back with a fix.

**Comment by notshi** [comment]
Hi @oddeye, apologies for the late response.

For some bizarre reason, there was a change in the way OpenGL works. Not a big one but a small change. You can grab the latest version of Swanky Paint for the fix.

**Comment by oddeye** [comment]
Works like a charm again. Thank you @notshi 👍

**Comment by notshi** [comment]
Fantastic, thanks for the report!
