### ISSUE TITLE
Cannot invalidate image cache with new image

### ISSUE THREAD

**Issue by truck** [xriss/swankypaint#17]
- the title is a GUESS as to what the bug actually involves.

I'm exporting my Pico-8 graphics via both 'export' and using the https://github.com/josefnpat/pico8utils png bit.
 - for now let's ignore the pico8 utils item, that has even more bizzarre complications.

When I load it the first time, all is good.
When I update it, put it back to P8, make a change there, and try to re-load:  it does not update the image.  It seemingly is pulling from _cache_ not from disk.
I can create a symlink (ln -s image.png temp.png) and load the symlink in, and that will load the image from disk.
I can then save that OVER the other image, and use an image viewer to see that it has updated... but even THEN swankage won't replace the image from disk.  It will ONLY load something that is PROBABLY a cached image.
I must restart the program to load the image fresh.  This really is a very disruptive issue for my workflow.

- back to the pico8utils version
SOMETIMES, but not always, the image that appears from "cache" will have an entirely different pallette.  This happens much more with the pico8utils export, but I have had it not load the pico-8 pallette from a pico-8 export, instead leaving swanky16 or swanky32 (the 'default.')  As it won't do a darned thing to update that, per the above bug, it's ... I can't seemingly get the darned image to update/load with the correct pallette, even post-save.

Something is very strange and I believe the cache is needing to have a "no, go away, load from disk" option.

**Comment by notshi** [comment]
Thanks, @truck - this is definitely a priority fix!
