### ISSUE TITLE
startup options either documented incorrectly or b0rked

### ISSUE THREAD

**Issue by truck** [xriss/swankypaint#18]
Per the steam forums, --fullscreen should start the program in fullscreen, and appending paths should add the path to the history bar in the file load dialog.

The Linux x64 version doens't do this , instead giving errors such as:

     truck  ~  worktools  swankypaint  ./gamecake.x64 ~/sturf/ld37/workspace/ld37gfx.png
    ./gamecake.x64: /home/truck/sturf/ld37/workspace/ld37gfx.png:2: '=' expected near 'char(26)'

     truck  ~  worktools  swankypaint  ./gamecake.x64 --fullscreen ~/sturf/pico-8-game-shell
    usage: ./gamecake.x64 [options] [script [args]].
    Available options are:
      -e stat  execute string 'stat'
      -l name  require library 'name'
      -i       enter interactive mode after executing 'script'
      -v       show version information
      --       stop handling options
      -        execute stdin and stop handling options

     truck  ~  worktools  swankypaint  ./gamecake.x64 -- --fullscreen ~/sturf/pico-8-game-shell
    ./gamecake.x64: cannot open --fullscreen: No such file or directory

(Yes I have a fancy zsh prompt that gives git status and whatnot.)

This is even more problematic on my system as my current work directory, /home/truck/sturf/ld37/workspace can't be navigated to with the parent/click-on-dir method: when it comes to the 'sturf' directory, it lists _nothing_ despite there being files and subdirectories.  I must type it manually, which I can do, but it's not _convenient._

**Comment by notshi** [comment]
Hmm, that's strange. Which version of SP are you running? Might be new updates that we've checked in that might have borked that.

**Comment by lastebil** [comment]
I can't actually tell as the version I have here, which has the last line of 1227 in updates.txt, no longer will start due to some changes in either lua or xorg.

I _think_ it was alpha 9.

Is there a convenient, non-steam way of updating this (as this is a dimel0ad install.)

**Comment by truck** [comment]
I can't actually tell as the version I have here, which has the last line of 1227 in updates.txt, no longer will start due to some changes in either lua or xorg.

I think it was alpha 9.

Is there a convenient, non-steam way of updating this (as this is a dimel0ad install.)

(I the logs in properlyz)

**Comment by notshi** [comment]
Hi @truck - sorry, there is no convenient, non-steam way of updating.

It's either dimel04d a new one or steam updates :}

PS:  fullscreen _should_ be working for the Linux x64 version unless system incompatibilities.

**Comment by notshi** [comment]
Is this still an issue, @truck? Thanks for your patience :}

**Comment by notshi** [comment]
This should be addressed in the latest version.
