### ISSUE TITLE
configuration save / options

### ISSUE THREAD

**Issue by truck** [xriss/swankypaint#19]
2 (4) things that I would like to have as options / save as defaults somehow:

 1. "black line" color.  (as the pico-8 background is 'black' and the grid line is black, it's less a grid line and more a 'check the margin for guide, somewhere' process)
 2. Save new default: location of magnifier window (I put it on the right with my setup)
 3. Save default position for brush handle (I prefer it in center and have issues moving about the magnified grid if it is in the upper left)
 4. grid size (allow non-8 widths. Yes, I like 8, but 4x8 and similar for fonts would be helpful.)  This I would not really want as a 'save new default' thing but maybe someone else would.

- suggest tagging this 'enhancement' (:

**Comment by notshi** [comment]
Thanks, @truck! All of these are very useful and lists things that we want for SP :}

**Comment by notshi** [comment]
Suggestions 2-4 is live with the latest BETA - you can now save your configurations and SP will remember.

**Comment by truck** [comment]
um, the latest BETA is via Steam or dime?

**Comment by notshi** [comment]
That would be Steam - we tend to push changes there a lot and only update Dimeload when it's stable.
