### ISSUE TITLE
Glow toggles on and off, but I don't know why.

### ISSUE THREAD

**Issue by truck** [xriss/swankypaint#2]
As images with no glow, at least in swanky32, look _remarkably_ different from images with glow - especially the white areas:
- it would be good to know if bloom is "on"
- toggling on/off would be cool
- most importantly, it should not happen when changing 'modes' from frame to layer.

**Comment by truck** [comment]
I did not mean gloom.  I meant bloom.

**Comment by notshi** [comment]
@truck Bloom is defaulted to **on** and at **1** (settings under the **cog** icon).

You can adjust the bloom settings there but yes, totally agree that there should be a quick toggle to turn bloom on and off on the screen!

That last one does sound like a bug as that shouldn't happen. Which version of SP is this happening to?

**Comment by truck** [comment]
swankypaint.v15.496  , Archlinux64, Nvidia drivers (not nouveaux)

Also, is 'bloom' setting supposed to 'stick' when saving?  If it is, then I can definately attempt to show how this error occurs on my side with a set of workflow screenshots.

**Comment by notshi** [comment]
Yes, the bloom settings should stick to the image as that's how it's currently set up.

**Comment by notshi** [comment]
This issue is addressed in Alpha +11 with the new windows system - Image > Properties and other bug fixes.
