### ISSUE TITLE
Doesn't start on Mac OS Sierra,

### ISSUE THREAD

**Issue by excitedpixels** [xriss/swankypaint#21]
Mac Pro 2009
Sierra latest update
3gb Nvidia 660GTX
16gb Memory
Xeon 2.6 ghz
13.5 TB storage (4 bays)

When I launch from Steam it says starting then everything disappears and you're back to steam.  Not sure what is causing an issue here.

**Comment by xriss** [comment]
OK, lets see if we can get some error messages.

Can you try opening a terminal and going into the directory steam installed it into, for me this is done like so

`cd /Users/kriss/Library/Application\ Support/Steam/SteamApps/common/swankypaint`

It could be somewhere else, but try changing the /kriss/ to your /username/, or search google for tips on finding where steam is installing files to on OSX.

Once you have a terminal in that directory then

`./gamecake`

will start swanky paint and print lots of debug info to the console along with any errors that are stopping it from starting up.

If you can copy paste what it prints out as a response here then then we can work out whats gone wrong.

**Comment by excitedpixels** [comment]
Not entirely sure what’s going on but it could be folder related.  Is there a version that runs from applications rather than the over complex steam structure ?

Last login: Sat Apr  8 19:52:52 on ttys000
MacP:~ jeremy$ /Applications/swankypaint/gamecake ; exit;
/Applications/swankypaint/gamecake: line 17: 68614 Killed: 9               `dirname $0`/gamecake.osx $*
logout
Saving session...

**Comment by xriss** [comment]
Oh, and looks like I haven't upgraded my test mac to sierra yet so doing that now to see if the problem is something apple has decided to change, again.

**Comment by xriss** [comment]
Still installing Sierra, but I'm suspicious that they may have changed their security model, maybe try this setting to allow things that are not from the app store to run? Hopefully it is a setting that still exists.

![security](https://cloud.githubusercontent.com/assets/3142388/24831703/e84cff70-1c96-11e7-8bd2-c8d6f61953bd.png)

**Comment by xriss** [comment]
OK, I'm still installing Sierra but I think it is this problem

http://apple.stackexchange.com/questions/258623/how-to-fix-killed-9-error-in-sierra

Can you try installing upx (homebrew?) and running `upx -d gamecake.osx` to uncompress it locally?

The executable is upx compressed, so these seems like it might be the same issue.

**Comment by excitedpixels** [comment]
As an app developer myself that's the first thing I do :D  I have managed to get it to run via crossover but performance is so poor it's just unusable.  Should be quite nippy really.  Sorry I'm not messing with UPX.  I'm techy but not that techy...  I've just ran it under parallels which is much better but performance is still a bit of a worry for me.  :) I loved paint on my Amiga 600 / 1200 and CD32.  There was also a PC version which was a bit of an older port of Deluxe paint.  I guess it's not a mac native app?  Thanks for all your help. :)

**Comment by xriss** [comment]
upx is just a compressor thing, just like zip really but for executables, looks like OSX has developed incompatibilities with it, which is a shame.

I'm still waiting on xcode to update before I can find out but at the moment at least I am getting the same symptoms so it should get fixed soon.

I usually run on linux so if other operating systems break I don't find out until someone complains :)

**Comment by xriss** [comment]
OK, confirmed that it is the upx compression, I'll try pushing an uncompressed version to steam and it should start working again on sierra.

**Comment by excitedpixels** [comment]
Thanks.  How long should it take for the build to go live (I’m using the code test to test the beta).  So far it’s still launching from steam and then doing nothing.

**Comment by xriss** [comment]
Went up on the test version last night, I'm in the middle of refactoring so worried that I may have broken some other bits but it seems OK.

**Comment by excitedpixels** [comment]
Thanks.. especially for working this out and fixing so quickly.  

It runs well now on my Mac :) (just need to learn how to use it now.)
