### ISSUE TITLE
Tile / Tilemap preview

### ISSUE THREAD

**Issue by madpew** [xriss/swankypaint#3]
I'd love to preview an image as a repeated pattern to see how well it tiles.
A single checkbox/shortcut to toggle tiling-preview would be enough.

It would be even fancier if one could select an area on the image (in case it's a tilemap) to preview but I could easily live without that.

**Comment by notshi** [comment]
Great suggestion @madpew definitely something we have in our list of things to support :}

**Comment by notshi** [comment]
Thank you so much for your support and patience! This feature will be live this Saturday (4th August, 2018) when we officially release Alpha +11.

More about this here - https://steamcommunity.com/games/432030/announcements/detail/1707313586207928435
