### ISSUE TITLE
Loading 'spritesheets' or images with frames or layers is difficult

### ISSUE THREAD

**Issue by truck** [xriss/swankypaint#4]
## this is not b0rked.

However, the process of loading a picture that you have saved that contains layers or frames is unintuitive, and often takes me up to a half hour of fiddling with a combination of 'forget images' / 'new image' / layer to frames / frame to layers.

It would be good to streamline this, or adapt the loading preview so it is less guesswork.
- I do not have a good set of suggestions for this yet, other than "preview should represent what is loaded" which is not the case for me right now.
- also, for some reason, the preview seems to display zoomed, and is not possible to turn off.

_apparently I am incapable of writing good feature/bug reports that are _single_ bug/feature reports._

**Comment by notshi** [comment]
@truck This actually shouldn't be happening so it's a bug.

I am able to reproduce the bug with layers but images with frames load up fine. Which version of SP are you using?

In any case, layers and frame settings should be remembered and load up as it is saved.

**Comment by truck** [comment]
swankypaint.v15.496 .  (Archlinux 64)

**Comment by notshi** [comment]
The next release (Alpha +11) has a spruced up user interface and tonnes of bug fixes which should address this problem :}
