### ISSUE TITLE
Additional / outside palette support

### ISSUE THREAD

**Issue by truck** [xriss/swankypaint#5]
I would very much like to have the Dawnbringer pallete available.
http://pixeljoint.com/forum/forum_posts.asp?TID=12795

External loading and saving of palettes would also be good.

**Comment by notshi** [comment]
Yes, that's definitely one of the things in the long list of things we want to support :}

**Comment by truck** [comment]
Is there a lua hook or such that could be used to alter the palette?

**Comment by notshi** [comment]
At the moment, it's all hard coded as it's **very** old code. It needs to be changed to just run off a directory of .PNGs so you can add any presets (palettes) you wish.

**Comment by truck** [comment]
It might be nice to also support other types of palettes, as, well, editing a png is sort of not the best ... way to make a palette (:

There are a bunch of palette formats already no need to reinvent the wheel, but a transformation of "so and so" to "the palette table" would be ... how I was thinking I'd do it if there was a lua thingage (;

For example, the raw values for the dawnbringer palette are in that thread above; along with the gimp palette, grafx2, graphicsgale, and paint.net .

I'm thinking the advantage of using the non-png version is the limitation of colors, such as what you have with Commodore 64; however I'm going to open another suggestion which references this, as it's a separate extension to this idea...

Obviously the advantage of using the png version is "lookie a palette already in this png when you load it" so having both would be good for people who want to work from an existing image and NOT have a limitation thrown at them.

**Comment by truck** [comment]
It should be noted that alert people (i.e. not truck) noted that the palette was included, and there were ways of using it, mentioned on the steam thread.

We should prolly put that discussion here too.  (i.e. truck could do something.)

**Comment by notshi** [comment]
Thanks, @truck :}

**Comment by truck** [comment]
Palettes are now popping up in the palette menu (all of 'em, including funky-purple-whatsit, p8, and dawnbringer.)

For some reason they aren't doing so in 'new' - which wouldn't be THAT big a problem if Truck knew how to fix the issue of 'whoops I should have loaded a pallette not remapped it' (or maybe it's the other way around.)

In conjunction with the bizzarre loading bug I'm about to report, this is ... kinda ... difficult to work with (:

(Mind you not as difficult as trying to work with the bizzarre colors in the msx pallette. But that's not a bug. It's a comment.)

**Comment by notshi** [comment]
We currently support 15 palettes (including Dawnbringer 16 & 32) but you can also add custom 8-bit palettes or presets to ```$HOME/Pictures/swankypaint/presets```

**Palette** - filename.pal.png
**Preset** - filename.set.png

We scan for these files at startup and add them to the Palette Editor menu. More formats will be available when we add them (PAL, HEX etc.) but there's currently support for 8-bit PNG.
