### ISSUE TITLE
Disable filters when copying brushes between images!

### ISSUE THREAD

**Issue by CharlotteGore** [xriss/swankypaint#6]
For some reason when I make a brush in one image and bloom is on, the brush is 'bloomed' and it messes the palettes up. :(

**Comment by notshi** [comment]
@CharlotteGore thanks for the feedback :}

I've tried to reproduce this but unable to so I'm possibly not understanding the question, sorry.

Are the images using the same palettes?

In any case, this shouldn't happen so it sounds like a bug.

**Comment by CharlotteGore** [comment]
Hmm. I just tried it again now and it worked perfectly. I... I don't know what happened. Oh maybe i just loaded the fatpixel exported version of a file instead of the raw one. IGNORE ME!
