### ISSUE TITLE
Rasperry Pi: difficult to use due to assert failure

### ISSUE THREAD

**Issue by truck** [xriss/swankypaint#9]
Raspberry Pi: Archlinux.

Swanky initializes ok, loading SDL contexts, images, fonts, the soapbar skin... though the rendering of the bezels on the soapbar skin looks a bit off.

Moving the mouse causes an assert failure, which then aborts the program.  Additionally, if not run under tmux, it appears it causes a disconnect the console from the keyboard _driver_ (as disconnecting the keyboard does not restore keyboard functionality.)  That is: one must ssh into the box to reboot it (:  It is NOT locked up, it's just unable to accept input from the keyboard.

This causes a bit of a difficulty in achieving paint swankage.

Here is the output to the terminal:
---mow---
WARN: 

Assertion failure at RPI_WarpMouseGlobal (/buildbot/slave/SDL/sdl-raspberrypi/src/src/video/raspberry/SDL_rpimouse.c:232), triggered 1 time:
  'update'

Abort/Break/Retry/Ignore/AlwaysIgnore? [abriA] : %    
---mow---
Can provide, via different than github means, a copy of the filesystems; 

Cannot provide strace, because of reverse heisenbug:
starting the application within strace causes the assert failure to no longer abort the program (:

**Comment by truck** [comment]
additionally, occasionally swankage will NOT load beyond SDL Create, instead (according to strace):

---mow---
ioctl(3, _IOC(0, 0xc4, 0x0d, 0x00), 0x18003) = 0
ioctl(3, _IOC(0, 0xc4, 0x0c, 0x00), 0x18003) = 0
ioctl(3, _IOC(_IOC_WRITE, 0xc4, 0x04, 0x0c), 0xbebb50c4) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0xc4, 0x08, 0x10), 0xbebb50b8) = -1 EAGAIN (Resource temporarily unavailable)
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0xc4, 0x08, 0x10), 0xbebb50b8) = -1 EAGAIN (Resource temporarily unavailable)
futex(0xb6c5faa0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1, NULL, ffffffff) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0xc4, 0x08, 0x10), 0xbebb50b8) = 4
ioctl(3, _IOC(0, 0xc4, 0x0d, 0x00), 0x18003) = 0
ioctl(3, _IOC(_IOC_WRITE, 0xc4, 0x04, 0x0c), 0xbebb4f9c) = 0
futex(0xb6c9aa40, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1, NULL, ffffffff
---mow---

**Comment by truck** [comment]
further strace attempts show that the assert does NOT trigger when run in strace.

Unsure if the slowness I'm experiencing is a result of this error, or just that it's a large HDMI screen and an RPI (:

**Comment by xriss** [comment]
Archlinux huh?

Have only tried/built on raspbian.  You can either try and build gamecake yourself in archlinux, or maybe it will work better without using SDL2.

gamecake_flavour=raspi ./gamecake.raspi

Should run without using SDL2 and may work better, but probably worse as it is less tested :). Sadly SDL2 is not easy to get in all distros so I'm linking in my own build which is probably where all the problems are.

**Comment by truck** [comment]
Well, can do that... how does one build gamecake?  (:

**Comment by xriss** [comment]
Grab this hg repo and run this script from within it

https://bitbucket.org/xixs/bin/src/tip/hgbuild

That should grab the rest of the source (it puts it side by side with the bin dir) and then build + install it...

Hopefully.

Something will probably go wrong, probably missing dependencies, eg SDL2 :)
